---
- name: Ansible Lamda Functions
  hosts: localhost
  strategy: free
  connection: local
  gather_facts: False
  tasks:
    - name: install dependencies
      pip:
        requirements: boto3
        chdir: .
        executable: pip3

  vars:
    tempdir: tempdeploydir
    tempzipfile: lambda.zip
    deployenv: deployvenv
    aws_profile: default
    lambda_iam_role: arn:aws:iam::1234567890:role/lambda-role

    lambda:
      name: lambdahello
      state: present
      profile: "{{aws_profile}}"
      zip_file: "{{tempzipfile}}"
      region: us-east-1
      runtime: python3.8
      role: "arn:aws:iam::1234567890:role/lambda-role"
      handler: lambdahello.lambda_handler
  